# Generated by Django 5.2.5 on 2025-08-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
