# Generated by Django 5.2.5 on 2025-08-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('oum', models.CharField(choices=[('kg', 'KG'), ('gm', 'GM'), ('pis', 'PIS'), ('box', 'BOX')], max_length=10)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('exp_date', models.DateField()),
            ],
        ),
    ]
